### PR TITLE
Add web hook info and image 

### PR DESCRIPTION
**Pull request by max21910**
web hook help push data from the user (app) to the serveur(database) without the need of an API

### CODE REVIEW

**Comment by userbradley** [comment]
Thanks for another PR @max21910 

Somethings to note:

* Webhooks - What are you basing this off? Have you got a screenshot of mitmproxy to show the data it sends? 

From my understanding of WebHooks, it would be more of an external system that bereal operate (github) sending messages in to them.

let me know!

**Comment by max21910** [comment]
Hi I use mimproxy but I could not find web hooks  anymore but I find 2 things :
1- the help pages is host in : http://berealapp.zendesk.com
2-i fond this but I didn't know what is this use for : http://cdn.bereal.network

**Comment by userbradley** [comment]
Thanks @max21910  - What I will do is create a feature branch, add the misc domains in and if you dont mind checking it over before I merge it?

**Comment by max21910** [comment]
sure !

**Comment by userbradley** [comment]
Closing this in Favor of https://github.com/userbradley/BeReal/pull/3

**Pull request closed without merging**
