### PR TITLE
Add info

### PR DESCRIPTION
**Pull request by max21910**
Add info in:
- Messaging request
- fix link issues
- fix typo

### CODE REVIEW

**Comment by userbradley** [comment]
I have had a look, and the `cdn-resize` seems to be using Fastly on the backend. Using my industry knowledge, I am almost confident that this is going to be this: https://developer.fastly.com/reference/io/

I would mark it down as

```text
Image optimization CDN
```

**Comment by max21910** [comment]
"I added the modification into my pull request. Thanks for the feedback!"

**Review by userbradley — APPROVED** [review]
Nice work as always @max21910 !

**Comment by max21910** [comment]
Thanks ! @userbradley

**Pull request merged**
