### PR TITLE
Adding new Domains

### PR DESCRIPTION
**Pull request by userbradley**
Added some new domains for the platform:

* bere.al
* bereal.team
* bereal.com

### CODE REVIEW

**Comment by userbradley** [comment]
@max21910  Thoughts? Let me know if I missed any or you know what they do

**Comment by max21910** [comment]
all seems to be great I will look to find new things !

**Comment by userbradley** [comment]
Sweet thanks. I will merge it! Let me know if you find anything.

In good honesty, I found an exposed GCS bucket and have reported it to them. BeReal have been known to send Cease and Desists to people who do things they shouldn't with their app - So hoping to win some brownie points before they imprison me and [hang me](https://www.britannica.com/event/Reign-of-Terror)

**Comment by max21910** [comment]
How did you find the exposed  GCS bucket ?

**Comment by userbradley** [comment]
Well:

We know that they use [GCP](https://boards.eu.greenhouse.io/bereal/jobs/4048817101?t=4c21b372teu#:~:text=Infrastructure%3A-,GCP,-%2C%20Kubernetes%2C%20Pub/Sub) for their platform, and we already know that they use it for their general storage [See here](https://storage.bere.al) 

I am a google engineer, and recognized `storage.objects.list` as being from [IAM Roles for Google](https://cloud.google.com/storage/docs/access-control/iam-roles)

Knowing that they have added the memories recap, they have probably had to store it under a new bucket so by going to `memories.bere.al` we are greeted by the default XML for a Google storage bucket.

We can then get the name from the top of the file

```xml
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
  <Name>bereal-us-central1-memories</Name>
```

Which means we can do a `gsutil ls` command

```shell
gsutil ls gs://bereal-us-central1-memories/memories/
```

The reason it's `/memories` is because of the URL they setup on the Load balancer.

https://cloud.google.com/load-balancing/docs/https/ext-load-balancer-backend-buckets


Let me know if that makes sense

**Comment by max21910** [comment]
okay great job !
make sense I found this as well and we can see all of the 2021 recap video its not great for the security

**Comment by userbradley** [comment]
Not at all, I reported it to them just in case, but I hope they fix it soon!

**Comment by userbradley** [comment]
BeReal have resolved the issue so I will remove that URL from the repo as it's no longer functional

**Pull request merged**
