### PR TITLE
Add new api endpoint (New PR)

### PR DESCRIPTION
**Pull request by max21910**
This is the new API endpoint I found using mitmproxy. This API endpoint is used for messaging, and this function has just arrived in my country, France (🇫🇷). Therefore, I was able to capture all the new requests (there are more, but I need time to add them all)

### CODE REVIEW

**Comment by userbradley** [comment]
Noice! 

Few things, but I can deal with them if you'd like:

* Page needs to be added to the `mkdocs.yaml` file

```diff
  - API Endpoints:
      - api-endpoints/index.md
      - Content: api-endpoints/content.md
      - Analytics: api-endpoints/analytics.md
      - Feeds: api-endpoints/feeds.md
+     - Messaging: api-endpoints/messaging.md
``` 

And then I would also add the domain`ogma.bereal.team` to the `docs/domains/top-level-domains.md` file

I'm able to add these as I know it's 1AM in france (I cant talk, it's 2am in the United Kingdom of Brexit) but if you'd like to take a stab feel free!

thanks as always!

**Review by userbradley — CHANGES_REQUESTED** [review]
See main comment on PR

**Comment by max21910** [comment]
i tried my best but i don't know if its ok ,
and it's 3:30 am in france  :)
thanks !

**Comment by userbradley** [comment]
Site renders 
image

**Review by userbradley — APPROVED** [review]

**Pull request merged**
